# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
docs/openapi.yaml:
  info-license:
    - '#/info'
  no-server-example.com:
    - '#/servers/0/url'
docs/paths/cars.yaml:
  operation-operationId:
    - '#/get/operationId'
    - '#/post/operationId'
  operation-4xx-response:
    - '#/get/responses'
  security-defined:
    - '#/get'
    - '#/post'
docs/paths/cars/{id}.yaml:
  operation-operationId:
    - '#/get/operationId'
    - '#/delete/operationId'
    - '#/patch/operationId'
  security-defined:
    - '#/get'
    - '#/delete'
    - '#/patch'
docs/paths/drivers.yaml:
  operation-operationId:
    - '#/get/operationId'
    - '#/post/operationId'
  operation-4xx-response:
    - '#/get/responses'
  security-defined:
    - '#/get'
    - '#/post'
docs/paths/drivers/{id}.yaml:
  operation-operationId:
    - '#/get/operationId'
    - '#/delete/operationId'
    - '#/patch/operationId'
  security-defined:
    - '#/get'
    - '#/delete'
    - '#/patch'
docs/paths/drivers/search.yaml:
  operation-operationId:
    - '#/get/operationId'
  security-defined:
    - '#/get'
docs/paths/events.yaml:
  operation-operationId:
    - '#/get/operationId'
    - '#/post/operationId'
  operation-4xx-response:
    - '#/get/responses'
  security-defined:
    - '#/get'
    - '#/post'
docs/paths/events/{id}.yaml:
  operation-operationId:
    - '#/get/operationId'
    - '#/delete/operationId'
    - '#/patch/operationId'
  security-defined:
    - '#/get'
    - '#/delete'
    - '#/patch'
docs/paths/teams.yaml:
  operation-operationId:
    - '#/get/operationId'
    - '#/post/operationId'
docs/paths/teams/{id}.yaml:
  operation-operationId:
    - '#/get/operationId'
    - '#/delete/operationId'
    - '#/patch/operationId'
docs/paths/tracks.yaml:
  operation-operationId:
    - '#/get/operationId'
    - '#/post/operationId'
  security-defined:
    - '#/get'
    - '#/post'
docs/paths/tracks/{id}.yaml:
  operation-operationId:
    - '#/get/operationId'
    - '#/delete/operationId'
    - '#/patch/operationId'
  security-defined:
    - '#/get'
    - '#/delete'
    - '#/patch'
docs/paths/users/authJWT.yaml:
  operation-operationId:
    - '#/post/operationId'
  security-defined:
    - '#/post'
