POST http://localhost:8080/auth/logout
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MzIyNjE2MjcsImV4cCI6MTczNDg5MTY0M30.Sc8UicNae0t2MYbjp3vSFJu-BKveY1Bp81Pv7fuY3ns


###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
"username": "test",
"password": "test"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
"username": "test",
"password": "test"
}


