name: Swagger UI Deployment to GitHub Pages

on:
  push:
    branches:
      - 26-swagger-ui-generation-w-auto-deployment-to-github-pages
#    paths:
#      - 'docs/**'  # Only run workflow when changes are made in the docs folder
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1.3.0
        with:
          output: swagger-ui
          spec-file: docs/openapi.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: swagger-ui
